[package]
name = "rterm"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rterm"
path = "src/main.rs"

[dependencies]
wry = { version = "0.51", features = ["devtools"] }
tao = "0.31"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
russh = { path = "../external/russh-main/russh", version = "0.61.2" }
russh-sftp = { path = "../external/russh-sftp" }
ssh-key = { version = "=0.7.0-rc.10", features = ["ed25519", "rsa", "p256", "p384", "p521", "encryption"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "sync", "io-util", "macros", "fs", "process"] }
lazy_static = "1.4"
base64 = "0.22"
chacha20poly1305 = "0.10"
blake3 = "1.5"
argon2 = "0.5"
rand = "0.10"
serialport = "4.6"
tokio-serial = "5.4"


[target.'cfg(unix)'.dependencies]
libc = "0.2"

[profile.release]
debug = true
